url: "http://oliora.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Hot C++ Blog
  avatar: # avatar.png
  gravatar: # "09ca143af901cc5bf8ba6ca6019bdd5f" # Email MD5 hash
  description: "Andrey Upadyshev's blog about C++11, C++14 and C++17." # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   Hot C++ Blog is created by <a href="/about/">Andrey Upadyshev</a>
   </br>
   <span style="font-size:85%">Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a></span>

  # Icons
  rss: true
  email_address: oliora@gmail.com

  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "oliora"
  google_plus:
  instagram: "oliora"
  linkedin: "https://www.linkedin.com/pub/andrey-upadyshev/59/497/321" # Full URL
  pinterest:
  reddit:
  slideshare: oliora
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "hot_cpp"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-71841148-1
  disqus_shortname: oliora-github-io
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"
plugins: ["jekyll-paginate"]

# BUILD SETTINGS
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    line_numbers: true

sass:
  sass_dir: _sass
  style: :compressed
